{% set name = "hidefix" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hidefix-{{ version }}.tar.gz
  sha256: a049519ee6650f8a656aee9a9af1f140dd15bdf85bd314e3fa1855c099c211c2

build:
  number: 1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.3,<1.4                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.3,<1.4
  run:
    - python
    - numpy
    - xarray
    - netCDF4

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-benchmark
    - dask
  imports:
    - hidefix
  commands:
    - pip check
    - pytest -v -s --log-cli-level=debug --benchmark-disable

about:
  home: https://github.com/gauteh/hidefix
  summary: Concurrent HDF5 and NetCDF4 reader (experimental)
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - gauteh
