{% set name = "hidefix" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hidefix-{{ version }}.tar.gz
  sha256: 228cf0748279546047eda25acb90b4fdaa344ad4d37b36e34c74d5558498172a

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=0.15,<0.16                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=0.15,<0.16
  run:
    - python
    - xz
    - numpy
    - xarray
    - netCDF4

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-benchmark
    - dask
  imports:
    - hidefix
  commands:
    - pip check
    - pytest -v -s --log-cli-level=debug --benchmark-disable

about:
  home: https://github.com/gauteh/hidefix
  summary: Concurrent HDF5 and NetCDF4 reader (experimental)
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - gauteh
